version: '3.8'
services:
  redis:
    image: redis:7.2-alpine
    container_name: podcastpro-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  web:
    build: .
    container_name: podcastpro-web
    command: python run.py
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    depends_on:
      - redis

  worker:
    build: .
    container_name: podcastpro-worker
    command: celery -A src.api.app.celery worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    depends_on:
      - redis
