version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: python run.py
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./test_files:/app/test_files
      - ./podcastpro_dev.db:/app/podcastpro_dev.db
    env_file:
      - .env
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A core.celery_worker.celery worker --loglevel=info
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./test_files:/app/test_files
      - ./podcastpro_dev.db:/app/podcastpro_dev.db
    env_file:
      - .env
    working_dir: /app/src
    environment:
      - PYTHONPATH=/app/src
    depends_on:
      - redis
